/**
 * Graph model — nodes, edges, parameters, growth, and the run.
 *
 * The split this file exists to keep: RULES live here, SCREEN STATE lives in the
 * component. Nothing in here knows about pickers, selection, pan or zoom; the growth
 * methods are pure graph operations that happen to be triggered by a `+`.
 *
 * Validation is deliberately NOT reimplemented here — `validate_graph` in Rust is the
 * only judge, so the two can never drift. That makes it async, so the component drives
 * revalidation from an effect (this file stays effect-free, per repo convention).
 */

import { invoke } from '@tauri-apps/api/core';
import type {
  GraphMethodMeta,
  GraphNodeParams,
  GraphRecipe,
  GraphRecipeEdge,
  GraphRunResult,
  GraphVerdict,
} from '$lib/types';
import type { InsertPoint } from './graph/node-options';

export interface CanvasNode {
  id: string;
  ref: string;
}

export class GraphController {
  methods = $state<GraphMethodMeta[]>([]);
  loadError = $state('');

  label = $state('');
  nodes = $state<CanvasNode[]>([]);
  edges = $state<GraphRecipeEdge[]>([]);
  /** nodeId -> { key: value }. Kept beside the nodes so removal can drop it wholesale. */
  params = $state<Record<string, GraphNodeParams>>({});

  verdict = $state<GraphVerdict | null>(null);
  validating = $state(false);

  running = $state(false);
  runId = $state('');
  /** Node currently executing, for the progress highlight. */
  activeNodeId = $state('');
  progress = $state(0);
  result = $state<GraphRunResult | null>(null);
  runError = $state('');

  // -------------------------------------------------------------- manifest

  async loadMethods() {
    try {
      this.methods = await invoke<GraphMethodMeta[]>('list_graph_methods');
      this.loadError = '';
    } catch (e) {
      this.loadError = `Could not load the method list: ${e}`;
    }
  }

  metaOf(ref: string): GraphMethodMeta | undefined {
    return this.methods.find((m) => m.id === ref);
  }

  metaOfNode(nodeId: string): GraphMethodMeta | undefined {
    const node = this.nodes.find((n) => n.id === nodeId);
    return node ? this.metaOf(node.ref) : undefined;
  }

  labelOfNode(nodeId: string): string {
    const node = this.nodes.find((n) => n.id === nodeId);
    if (!node) return '';
    return this.metaOf(node.ref)?.label ?? node.ref;
  }

  // ------------------------------------------------------------- structure

  /** Highest existing n{k} + 1 — node count would reuse ids after a deletion. */
  private mint(): string {
    let max = -1;
    for (const node of this.nodes) {
      const n = Number(node.id.slice(1));
      if (node.id.startsWith('n') && Number.isFinite(n)) max = Math.max(max, n);
    }
    return `n${max + 1}`;
  }

  parentsOf(nodeId: string): string[] {
    return this.edges.filter((e) => e.to === nodeId).map((e) => e.from);
  }

  childrenOf(nodeId: string): string[] {
    return this.edges.filter((e) => e.from === nodeId).map((e) => e.to);
  }

  /**
   * Edges are generated by insertion, never dragged. Five entry points, each with a
   * defined edge transform.
   */
  insertAt(point: InsertPoint, ref: string): string {
    const id = this.mint();
    const meta = this.metaOf(ref);
    const node: CanvasNode = { id, ref };
    let edges = [...this.edges];

    switch (point.kind) {
      case 'root':
        break;

      case 'after': {
        // X's outgoing edges are re-parented onto the new node, then X feeds it.
        edges = edges.map((e) => (e.from === point.nodeId ? { from: id, to: e.to } : e));
        edges.push({ from: point.nodeId, to: id });
        break;
      }

      case 'before': {
        edges = edges.map((e) => (e.to === point.nodeId ? { from: e.from, to: id } : e));
        edges.push({ from: id, to: point.nodeId });
        break;
      }

      case 'below': {
        // A parallel branch: eat the same input X eats. With no parents, the new node
        // simply starts its own chain.
        for (const parent of this.parentsOf(point.nodeId)) {
          edges.push({ from: parent, to: id });
        }
        break;
      }

      case 'edge': {
        edges = edges.filter((e) => !(e.from === point.from && e.to === point.to));
        edges.push({ from: point.from, to: id });
        edges.push({ from: id, to: point.to });
        break;
      }
    }

    this.nodes = [...this.nodes, node];
    this.edges = dedupe(edges);

    // Seed required parameters that carry a manifest default, so a freshly placed node
    // is as close to runnable as the manifest allows.
    const seeded: GraphNodeParams = {};
    for (const spec of meta?.params ?? []) {
      if (spec.default !== undefined && spec.required) seeded[spec.key] = spec.default;
    }
    if (Object.keys(seeded).length) this.params = { ...this.params, [id]: seeded };

    return id;
  }

  /** The inverse of on-edge insertion: stitch every parent to every child. */
  removeNode(nodeId: string) {
    const parents = this.parentsOf(nodeId);
    const children = this.childrenOf(nodeId);

    let edges = this.edges.filter((e) => e.from !== nodeId && e.to !== nodeId);
    for (const parent of parents) {
      for (const child of children) {
        if (parent !== child) edges.push({ from: parent, to: child });
      }
    }

    this.nodes = this.nodes.filter((n) => n.id !== nodeId);
    this.edges = dedupe(edges);

    // Ids get reused, so leaving parameters behind would silently apply them to a
    // future node.
    const { [nodeId]: _dropped, ...rest } = this.params;
    this.params = rest;
  }

  /** Add a second input to a node that reads more than one slot. */
  connect(from: string, to: string) {
    if (from === to) return;
    if (this.edges.some((e) => e.from === from && e.to === to)) return;
    this.edges = [...this.edges, { from, to }];
  }

  disconnect(from: string, to: string) {
    this.edges = this.edges.filter((e) => !(e.from === from && e.to === to));
  }

  clear() {
    this.nodes = [];
    this.edges = [];
    this.params = {};
    this.label = '';
    this.verdict = null;
    this.result = null;
    this.runError = '';
  }

  // ------------------------------------------------------------ parameters

  paramsOf(nodeId: string): GraphNodeParams {
    return this.params[nodeId] ?? {};
  }

  /** Clearing a value removes the key entirely — back to "never set". */
  setParam(nodeId: string, key: string, value: unknown) {
    const current = { ...this.paramsOf(nodeId) };
    const empty =
      value === undefined ||
      value === null ||
      (typeof value === 'string' && value.trim() === '') ||
      (typeof value === 'number' && Number.isNaN(value));

    if (empty) delete current[key];
    else current[key] = value;

    if (Object.keys(current).length === 0) {
      const { [nodeId]: _dropped, ...rest } = this.params;
      this.params = rest;
    } else {
      this.params = { ...this.params, [nodeId]: current };
    }
  }

  /** One line, only for things actually set — defaults are not worth the pixels. */
  summaryOf(nodeId: string): string {
    const meta = this.metaOfNode(nodeId);
    if (!meta) return '';
    const values = this.paramsOf(nodeId);

    const parts: string[] = [];
    for (const spec of meta.params) {
      const value = values[spec.key];
      if (value === undefined || value === '') {
        // Inheritance is an invisible choice — worth saying out loud.
        if (spec.fallbackFrom && this.parentsOf(nodeId).length > 0) {
          parts.push(`${spec.label}: from upstream`);
        }
        continue;
      }
      if (spec.kind === 'path' || spec.kind === 'dir') {
        parts.push(`${spec.label}: ${basename(String(value))}`);
      } else if (spec.kind === 'enum') {
        const option = spec.options?.find((o) => o.value === value);
        parts.push(`${spec.label}: ${option?.label ?? value}`);
      } else if (spec.kind === 'bool') {
        if (value) parts.push(spec.label);
      } else {
        parts.push(`${spec.label}: ${value}`);
      }
    }
    return parts.join(' · ');
  }

  hasSummary(nodeId: string): boolean {
    return this.summaryOf(nodeId).length > 0;
  }

  // ---------------------------------------------------------------- recipe

  toRecipe(): GraphRecipe {
    return {
      label: this.label.trim() || 'Untitled graph',
      nodes: this.nodes.map((node) => {
        const meta = this.metaOf(node.ref);
        const params = this.paramsOf(node.id);
        return {
          nodeId: node.id,
          kind: meta?.kind ?? 'method',
          nodeRef: node.ref,
          ...(Object.keys(params).length ? { params } : {}),
        };
      }),
      edges: this.edges.map((e) => ({ from: e.from, to: e.to })),
    };
  }

  /** Content fingerprint — what the component watches to decide when to revalidate. */
  get snapshot(): string {
    return JSON.stringify(this.toRecipe());
  }

  async revalidate() {
    if (this.nodes.length === 0) {
      this.verdict = null;
      return;
    }
    this.validating = true;
    try {
      this.verdict = await invoke<GraphVerdict>('validate_graph', { recipe: this.toRecipe() });
    } catch (e) {
      this.verdict = { valid: false, reason: String(e), warnings: [], order: [] };
    }
    this.validating = false;
  }

  // ------------------------------------------------------------------- run

  async run() {
    this.running = true;
    this.runError = '';
    this.result = null;
    this.progress = 0;
    this.activeNodeId = '';
    try {
      this.result = await invoke<GraphRunResult>('execute_graph', { recipe: this.toRecipe() });
      this.progress = 100;
    } catch (e) {
      this.runError = String(e);
    }
    this.running = false;
    this.activeNodeId = '';
  }

  async cancel() {
    if (!this.runId) return;
    try {
      await invoke('cancel_graph_run', { runId: this.runId });
    } catch {
      // A finished run has already been dropped from the registry; nothing to do.
    }
  }
}

function dedupe(edges: GraphRecipeEdge[]): GraphRecipeEdge[] {
  const seen = new Set<string>();
  const out: GraphRecipeEdge[] = [];
  for (const edge of edges) {
    if (edge.from === edge.to) continue;
    const key = `${edge.from}→${edge.to}`;
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(edge);
  }
  return out;
}

function basename(path: string): string {
  const parts = path.split(/[/\\]/);
  return parts[parts.length - 1] || path;
}
