// AUTO-GENERATED icon registry: Material-Symbol-style name -> Lucide component.
// Maps the icon-name strings used across the app to @lucide/svelte components.
// Regenerate if icon usage changes.
import {
  Activity,
  Aperture,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Camera,
  Cast,
  ChartColumn,
  ChartLine,
  ChartPie,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  CircleAlert,
  CircleCheck,
  CircleCheckBig,
  CirclePlay,
  CircleQuestionMark,
  CircleSlash,
  CircuitBoard,
  Clock,
  Code,
  Copy,
  EllipsisVertical,
  Eye,
  FilePlus,
  FileText,
  FileVideoCamera,
  Film,
  FingerprintPattern,
  Focus,
  Folder,
  FolderOpen,
  FolderPlus,
  FolderX,
  Frame,
  Gauge,
  GitCompare,
  Globe,
  HardDrive,
  History,
  Hourglass,
  Image,
  Images,
  Inbox,
  Info,
  Languages,
  LayoutDashboard,
  LayoutGrid,
  List,
  ListFilter,
  ListVideo,
  LoaderCircle,
  LogIn,
  Maximize,
  MemoryStick,
  Monitor,
  Moon,
  Network,
  Palette,
  Pause,
  Pencil,
  Play,
  Plus,
  Radio,
  RadioTower,
  Ratio,
  RefreshCw,
  RotateCcw,
  Save,
  Scan,
  Search,
  Server,
  Settings,
  SlidersHorizontal,
  Star,
  Sun,
  SunMedium,
  Tag,
  TextAlignJustify,
  Timer,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Upload,
  UserX,
  Users,
  Video,
  VideoOff,
  Volume2,
  VolumeX,
  Workflow,
  X,
  Zap
} from "@lucide/svelte";
import type { Component } from "svelte";

export const icons: Record<string, Component> = {
  account_tree: Network,
  add: Plus,
  analytics: ChartColumn,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  aspect_ratio: Ratio,
  bar_chart: ChartColumn,
  bolt: Zap,
  brightness_auto: SunMedium,
  cast_connected: Cast,
  cell_tower: RadioTower,
  center_focus_strong: Focus,
  check: Check,
  check_circle: CircleCheck,
  chevron_right: ChevronRight,
  close: X,
  code: Code,
  compare: GitCompare,
  content_copy: Copy,
  conversion_path: Workflow,
  create_new_folder: FolderPlus,
  dark_mode: Moon,
  dashboard: LayoutDashboard,
  data_usage: ChartPie,
  delete: Trash2,
  description: FileText,
  developer_board: CircuitBoard,
  dns: Server,
  donut_large: ChartPie,
  draw: Pencil,
  error: CircleAlert,
  expand_more: ChevronDown,
  filter_center_focus: Scan,
  filter_frames: Frame,
  filter_list: ListFilter,
  fingerprint: FingerprintPattern,
  first_page: ChevronsLeft,
  folder: Folder,
  folder_off: FolderX,
  folder_open: FolderOpen,
  fullscreen: Maximize,
  grid_view: LayoutGrid,
  group_off: UserX,
  group_work: Users,
  hard_drive: HardDrive,
  help: CircleQuestionMark,
  history: History,
  hourglass_empty: Hourglass,
  hourglass_top: Hourglass,
  image: Image,
  inbox: Inbox,
  info: Info,
  input: LogIn,
  label: Tag,
  last_page: ChevronsRight,
  light_mode: Sun,
  list: List,
  list_alt: List,
  memory: MemoryStick,
  monitor: Monitor,
  more_vert: EllipsisVertical,
  motion_photos_off: CircleSlash,
  motion_photos_on: Aperture,
  movie: Film,
  note_add: FilePlus,
  palette: Palette,
  panorama_photosphere: Globe,
  pause: Pause,
  pending: Clock,
  perm_media: Images,
  photo_camera: Camera,
  photo_library: Images,
  play_arrow: Play,
  play_circle: CirclePlay,
  playlist_play: ListVideo,
  progress_activity: LoaderCircle,
  query_stats: ChartLine,
  restart_alt: RotateCcw,
  save: Save,
  schedule: Clock,
  search: Search,
  segment: TextAlignJustify,
  sensors: Radio,
  settings: Settings,
  settings_brightness: SunMedium,
  show_chart: ChartLine,
  speed: Gauge,
  star: Star,
  stream: Radio,
  sync: RefreshCw,
  task_alt: CircleCheckBig,
  timeline: Activity,
  timer: Timer,
  translate: Languages,
  trending_up: TrendingUp,
  tune: SlidersHorizontal,
  upload: Upload,
  video: Video,
  video_file: FileVideoCamera,
  videocam: Video,
  videocam_off: VideoOff,
  view_module: LayoutGrid,
  visibility: Eye,
  volume_off: VolumeX,
  volume_up: Volume2,
  warning: TriangleAlert,
};
